### ISSUE TITLE
Can't set environment variables

### ISSUE THREAD

**Issue by mtolly** [ghcjs/ghcjs#263]
From https://hackage.haskell.org/package/base-4.7.0.1/docs/System-Environment.html, `getEnv` and `lookupEnv` work fine in GHCJS code, delegating to a JS function `h$getenv`. But `setEnv` does not because it delegates to a nonexistent JS `h$putenv`:

```
uncaught exception in Haskell main thread: ReferenceError: h$putenv is not defined
ReferenceError: h$putenv is not defined
    at h$$mi (/Users/mtolly/git/setenv/dist/build/setenv/setenv.jsexe/all.js:38868:11)
    at h$mainLoop (/Users/mtolly/git/setenv/dist/build/setenv/setenv.jsexe/all.js:10661:25)
    at /Users/mtolly/git/setenv/dist/build/setenv/setenv.jsexe/all.js:11127:13
    at /Users/mtolly/git/setenv/dist/build/setenv/setenv.jsexe/all.js:13454:17
    at Object.wrapper [as oncomplete] (fs.js:521:5)
```

**Comment by soenkehahn** [comment]
I seem to be running into this issue. Was this solved?

**Comment by luite** [comment]
hm, I forgot if I merged or reimplemented this. I guess probably not

**Comment by soenkehahn** [comment]
I ran into this while trying to use `hspec`. (Some context: I think `hspec` stores information about which test cases failed in an environment variable. It does this to allow to subsequently re-run only the failing test-cases in `ghci`. This also means that `hspec` doesn't work at all with `ghcjs`.)

I think it would be great to make `hspec` work with `ghcjs`. It's a pretty important part of my development workflow and I wouldn't want to miss it just because I'm targeting the browser.

This could also unlock a huge source of test-suites to reveal bugs in `ghcjs` I imagine.

**Comment by sol** [comment]
I would be ok to workaround this in `hspec` as an intermediate solution, if that helps.

That would mean that we do not call `setEnv` when compiled with `ghcjs` (through guarding that code with `CPP`).

**Comment by soenkehahn** [comment]
Can we reopen this until it's fixed, please?
