### ISSUE TITLE
Can install `shakespeare` package with latest `ghcjs`

### ISSUE THREAD

**Issue by geraldus** [ghcjs/ghcjs#292]
I'm having following error message:
```
[13 of 17] Compiling Text.CssCommon   ( Text/CssCommon.hs, dist/build/Text/CssCommon.js_o )
Linking template haskell ()
Linking template haskell (Text.Coffee,Text.Css,Text.Hamlet,Text.Hamlet.Parse,Text.Hamlet.RT,Text.IndentToBrace,Text.Julius,Text.MkSizeType,Text.Roy,Text.Shakespeare,Text.Shakespeare.Base,Text.Shakespeare.Text,ThRunner1)
uncaught exception in Haskell main thread: ReferenceError: h$shakespearezm2zi0zi2zi1ZCTextziMkSizzeTypezimkSizzeType is not defined
ReferenceError: h$shakespearezm2zi0zi2zi1ZCTextziMkSizzeTypezimkSizzeType is not defined
    at eval (eval at h$loadCodeStr (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:139:10), <anonymous>:80376:2)
    at eval (native)
    at Object.h$loadCodeStr [as loadCodeStr] (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:139:10)
    at Object.h$loadCode [as loadCode] (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:147:10)
    at h$$ghcjszmprimzm0zi1zi0zi0ZCGHCJSziPrimziTHziEval_X (eval at h$loadCodeStr (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:139:10), <anonymous>:90385:16)
    at h$mainLoop (eval at h$loadCodeStr (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:139:10), <anonymous>:10429:25)
    at eval (eval at h$loadCodeStr (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:139:10), <anonymous>:10897:13)
    at /Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:95:9
    at h$processQueue (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:71:13)
    at Socket.<anonymous> (/Users/arthurfayzrakhmanov/.ghcjs/x86_64-darwin-0.1.0-7.8.3/ghcjs/thrunner.js:51:17)

Text/CssCommon.hs:1:1:
    Exception when trying to run compile-time code:
      Data.Binary.Get.runGet at position 0: demandInput: not enough bytes
    Code: mkSizeType "EmSize" "em"
Failed to install shakespeare-2.0.2.1
```

**Comment by luite** [comment]
I'll look into it. It's Iikely a problem with the linker updates i did yesterday:

https://github.com/ghcjs/ghcjs/commit/0f9efdc9e15e48c8ac6a3cf17810573e904b098c

**Comment by geraldus** [comment]
It's pretty big!

**Comment by luite** [comment]
should work again now

**Comment by geraldus** [comment]
Fixed! Thanks!
