### ISSUE TITLE
h$kill is not defined

### ISSUE THREAD

**Issue by pikajude** [ghcjs/ghcjs#455]
When trying to run https://github.com/pikajude/jude.bio-servant built with ghcjs 561365ba1667053b5dc5846e2a8edb33eaa3f6dd:

```
uncaught exception in Haskell main thread: ReferenceError: h$kill is not defined
ReferenceError: h$kill is not defined
    at h$$aSI (/Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:109897:11)
    at h$runThreadSlice (/Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:11396:11)
    at h$runThreadSliceCatch (/Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:11341:12)
    at h$mainLoop (/Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:11334:9)
    at /Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:11982:13
    at /Users/pikajude/.dev/Haskell/jude-web/dist/build/jude-web/jude-web.jsexe/all.js:25348:17
    at Object.wrapper [as oncomplete] (fs.js:466:17)
```

Please let me know what other debug information is needed, or if this bug has been fixed in a newer revision.

**Comment by luite** [comment]
hmm sounds like not all files are included, or something is included in the wrong order. I think `h$kill` should be defined in `rts.js`, is it there?
