### ISSUE TITLE
Symbols from double-conversion library are missing

### ISSUE THREAD

**Issue by k-bx** [ghcjs/ghcjs#457]
Please explain how to add missing FFI symbols from double-conversion library.

Example to reproduce bug:

```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import           Formatting
import           Formatting.ShortFormatters

main :: IO ()
main = do
  putStrLn (formatToString ("hello world "%d) (123::Int))
```

Output:

```
➜  ghcjs-bug-formatting  node $(stack path --local-install-root)/bin/ghcjs-bug-formatting.jsexe/all.js
uncaught exception in Haskell main thread: ReferenceError: h$_hs_ToShortestLength is not defined
ReferenceError: h$_hs_ToShortestLength is not defined
    at h$$os (/Users/kb/workspace/ghcjs-bug-formatting/.stack-work/install/x86_64-osx/lts-4.1/ghcjs-0.2.0.20151029_ghc-7.10.2/bin/ghcjs-bug-formatting.jsexe/all.js:41506:11)
    at Immediate.h$mainLoop (/Users/kb/workspace/ghcjs-bug-formatting/.stack-work/install/x86_64-osx/lts-4.1/ghcjs-0.2.0.20151029_ghc-7.10.2/bin/ghcjs-bug-formatting.jsexe/all.js:11347:25)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Thank you!

**Comment by kfigiela** [comment]
Please look at https://github.com/bos/double-conversion/blob/master/Data/Double/Conversion/FFI.hs – AFAIR `foreign import ccall`s are treaded by ghcjs as `foreign import javascript`. Probably this `double-conversion` library should be patched to provide native implementation for GHCJS environment.

**Comment by k-bx** [comment]
@kfigiela I'd be happy to patch it, just don't know how to do that. Any pointer to existing library which work well under both foreign ccall and javascript so that I could do similar thing would be very helpful!

**Comment by kfigiela** [comment]
I think https://github.com/ghcjs/ghcjs-dom could be good (but not minimal) example.

What I would try is to:
* put js ffi implementations to `jsbits` folder in the project
* edit cabal file
* use c preprocessor to chose foregin implementation 

```{-# LANGUAGE CPP #-}

#if (defined(ghcjs_HOST_OS) && defined(USE_JAVASCRIPTFFI)))
-- here goes javascript imports
#else 
-- here goes cpp imports
#endif 
```

**Comment by Profpatsch** [comment]
Would love to have a patch for that.
