### ISSUE TITLE
Connecting a browser to GHCJSi doesn't work with socket.io > 1.3.7

### ISSUE THREAD

**Issue by basvandijk** [ghcjs/ghcjs#488]
My OS (NixOS) has `socket.io-1.4.5`. Connecting a browser to GHCJSi produces the following error in the GHCJSi console:

```
browser connected, code runs in browser from now on
[TypeError: socket.close is not a function]
TypeError: socket.close is not a function
    at Namespace.<anonymous> (/nix/store/nbjpfp5bh2gjbv0zwgkwzz11pbzkssqq-ghcjs-0.2.0/lib/ghcjs-0.2.0/irunner.js:81:14)
    at emitOne (events.js:77:13)
    at Namespace.emit (events.js:169:7)
    at Namespace.emit (/nix/store/5024nrv33vxr8a1r1flrwpb0a68khkgy-nodejs-socket.io-1.4.5/lib/node_modules/socket.io/lib/namespace.js:206:10)
    at /nix/store/5024nrv33vxr8a1r1flrwpb0a68khkgy-nodejs-socket.io-1.4.5/lib/node_modules/socket.io/lib/namespace.js:174:14
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

After locally installing `socket.io-1.3.7` it works:

```
$ npm i socket.io@1.3.7
$ NODE_PATH=./node_modules cabal repl
```

**Comment by luite** [comment]
can you check if this commit fixed this:

https://github.com/ghcjs/ghcjs/commit/8869593e22829ef0824ed55768b9637ad55607d9
