### ISSUE TITLE
ReferenceError: h$CCS_SYSTEM is not defined

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs#515]
The error shows up both with today's master on GHC 7.10.3 and yesterday's dedupe branch on GHC 8.0.1, when compiling https://github.com/LambdaHack/LambdaHack as follows:

```
$ cabal configure --ghcjs --enable-profiling
$ cabal build -j1
...
[124 of 124] Compiling Game.LambdaHack.Server ( Game/LambdaHack/Server.hs, dist/build/Game/LambdaHack/Server.js_p_o )
Preprocessing executable 'LambdaHack' for LambdaHack-0.5.1.0...
[ 1 of 15] Compiling Content.ItemKindTemporary ( GameDefinition/Content/ItemKindTemporary.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindTemporary.js_o )
[ 2 of 15] Compiling Content.ItemKindOrgan ( GameDefinition/Content/ItemKindOrgan.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindOrgan.js_o )
[ 3 of 15] Compiling Content.ItemKindBlast ( GameDefinition/Content/ItemKindBlast.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindBlast.js_o )
[ 4 of 15] Compiling Content.ItemKindActor ( GameDefinition/Content/ItemKindActor.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindActor.js_o )
[ 5 of 15] Compiling Content.ModeKindPlayer ( GameDefinition/Content/ModeKindPlayer.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ModeKindPlayer.js_o )
[ 6 of 15] Compiling Paths_LambdaHack ( dist/build/autogen/Paths_LambdaHack.hs, dist/build/LambdaHack/LambdaHack-tmp/Paths_LambdaHack.js_o )
[ 7 of 15] Compiling Content.TileKind ( GameDefinition/Content/TileKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/TileKind.js_o )
[ 8 of 15] Compiling Content.RuleKind ( GameDefinition/Content/RuleKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/RuleKind.js_o )
Linking Template Haskell ()
Linking Template Haskell (Content.ItemKindActor,Content.ItemKindBlast,Content.ItemKindOrgan,Content.ItemKindTemporary,Content.ModeKindPlayer,Content.TileKind,Paths_LambdaHack,ThRunner1)
Linking Template Haskell (Content.ItemKindActor,Content.ItemKindBlast,Content.ItemKindOrgan,Content.ItemKindTemporary,Content.ModeKindPlayer,Content.TileKind,Paths_LambdaHack,ThRunner2)
[ 9 of 15] Compiling Content.PlaceKind ( GameDefinition/Content/PlaceKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/PlaceKind.js_o )
[10 of 15] Compiling Content.ModeKind ( GameDefinition/Content/ModeKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ModeKind.js_o )
[11 of 15] Compiling Content.ItemKind ( GameDefinition/Content/ItemKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKind.js_o )
[12 of 15] Compiling Content.CaveKind ( GameDefinition/Content/CaveKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/CaveKind.js_o )
[13 of 15] Compiling Client.UI.Content.KeyKind ( GameDefinition/Client/UI/Content/KeyKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Client/UI/Content/KeyKind.js_o )
[14 of 15] Compiling TieKnot          ( GameDefinition/TieKnot.hs, dist/build/LambdaHack/LambdaHack-tmp/TieKnot.js_o )
[15 of 15] Compiling Main             ( GameDefinition/Main.hs, dist/build/LambdaHack/LambdaHack-tmp/Main.js_o )
[ 1 of 15] Compiling Content.ItemKindTemporary ( GameDefinition/Content/ItemKindTemporary.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindTemporary.js_p_o )
[ 2 of 15] Compiling Content.ItemKindOrgan ( GameDefinition/Content/ItemKindOrgan.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindOrgan.js_p_o )
[ 3 of 15] Compiling Content.ItemKindBlast ( GameDefinition/Content/ItemKindBlast.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindBlast.js_p_o )
[ 4 of 15] Compiling Content.ItemKindActor ( GameDefinition/Content/ItemKindActor.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ItemKindActor.js_p_o )
[ 5 of 15] Compiling Content.ModeKindPlayer ( GameDefinition/Content/ModeKindPlayer.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/ModeKindPlayer.js_p_o )
[ 6 of 15] Compiling Paths_LambdaHack ( dist/build/autogen/Paths_LambdaHack.hs, dist/build/LambdaHack/LambdaHack-tmp/Paths_LambdaHack.js_p_o )
[ 7 of 15] Compiling Content.TileKind ( GameDefinition/Content/TileKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/TileKind.js_p_o )
[ 8 of 15] Compiling Content.RuleKind ( GameDefinition/Content/RuleKind.hs, dist/build/LambdaHack/LambdaHack-tmp/Content/RuleKind.js_p_o )
Linking Template Haskell ()
Linking Template Haskell (Content.ItemKindActor,Content.ItemKindBlast,Content.ItemKindOrgan,Content.ItemKindTemporary,Content.ModeKindPlayer,Content.TileKind,Paths_LambdaHack,ThRunner1)
ReferenceError: h$CCS_SYSTEM is not defined
    at eval (eval at h$loadCodeStr (/mikolaj/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/thrunner.js:141:10), <anonymous>:8281:127)
    at h$loadCodeStr (/mikolaj/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/thrunner.js:141:10)
    at h$loadInitialCode (/mikolaj/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/thrunner.js:123:5)
    at h$processQueue (/mikolaj/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/thrunner.js:73:13)
    at Socket.<anonymous> (/mikolaj/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/thrunner.js:52:17)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:433:10)
    at emitReadable (_stream_readable.js:427:7)
    at readableAddChunk (_stream_readable.js:188:13)
$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
$ node --version
v6.4.0
```

**Comment by tolysz** [comment]
same on

    node --version
    v6.5.0

It looks like `rts_js_p.yaml` or `rts_js_debug_p.yaml` is not included when compiling TH

**Comment by Mikolaj** [comment]
I just verified and this is not caused by TH being used when compiling executable, but by TH usage in general. When I tweak the code in https://github.com/LambdaHack/LambdaHack/commit/60cd17b6c0f98bab924278a252e9571c7a563ca3 so that TH is invoked when building the library, not the executable, the problem persists, but gets reported not during compilation, but when running the JS code:

```
~/r/LambdaHack$ node dist/build/LambdaHack/LambdaHack.jsexe/all.js --dbgMsgSer --newGame 3 --noAnim --maxFps 100000 --frontendNull --benchmark --stopAfterFrames 50 --automateAll --keepAutomated --gameMode battle --setDungeonRng 0 --setMainRng 0 +RTS -p -RTS
/mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/all.js:11890
var h$noop = h$c0(h$noop_e, h$CCS_SYSTEM);
                            ^

ReferenceError: h$CCS_SYSTEM is not defined
    at Object.<anonymous> (/mikolaj/r/LambdaHack/dist/build/LambdaHack/LambdaHack.jsexe/all.js:11890:29)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

BTW, the same exception is thrown if I omit +RTS -p -RTS.

**Comment by tolysz** [comment]
So to summarise the library was build with profiling being on?
I wonder which defines would allow 
https://github.com/ghcjs/shims/blob/master/src/profiling.js
to be "linked" to your `all.js` and make it work?

**Comment by Mikolaj** [comment]
Yes, it was built with

```
cabal configure --enable-library-profiling --enable-profiling --ghc-option=-fprof-auto-exported --ghcjs --ghcjs-option=-dedupe
```

I have no clue about JS and defines. I naively added

```
<script language="javascript" src="profiling.js"></script>
```

to the default index.html, but it didn't help.

**Comment by Mikolaj** [comment]
After removing the ASSERT and TRACE cruft from profiling.js it loads fine from index.html in Chrome, but something else fails:

```
rts.js:11890 Uncaught ReferenceError: h$CCS_SYSTEM is not defined
lib.js:2493 Uncaught ReferenceError: h$CCS_SYSTEM is not defined
out.js:1 Uncaught ReferenceError: h$CC is not defined
rts.js:7959 Uncaught TypeError: Cannot read property 'cc' of undefined
﻿```

**Comment by tolysz** [comment]
So now the order of definitions/imports. It looks like it needs to be included before `rts.js` and `lib.js`

**Comment by Mikolaj** [comment]
My best attempt so far is

```
    <script language="javascript" src="platform.js"></script>
    <script language="javascript" src="profiling.js"></script>
    <script language="javascript" src="rts.js"></script>
    <script language="javascript" src="lib.js"></script>
    <script language="javascript" src="out.js"></script>
```

but it still fails and I'm afraid it may require still more files, with defines in each. We must be missing something silly and simple.

**Comment by ryantrinkle** [comment]
It looks like adding
```
  - src/profiling.js
```
to [shims/rts.yaml](https://github.com/ghcjs/shims/blob/master/rts.yaml) fixes the issue, although this fix is almost certainly not quite the right thing to do, since I think it results in including profiling.js in *all* copies of the RTS, including non-profiling builds.

**Comment by luite** [comment]
I think I know what's going on then.

`rts.yaml` has the dependencies of the rts regardless of the `Ways`, `rts_js_p.yaml` has the dependencies for `WayProf` and JS. There's a separate file for `WayDebug` + `WayProf`. I suspect nix or TH forces the `WayDyn` way.

Does it work if you copy `rts_js_p.yaml` to `rts_js_p_dyn.yaml` in the same directory?

**Comment by luite** [comment]
Oh also copy to `rts_js_debug_p_dyn.yaml` then, I think TH currently relies on the debug flag.

**Comment by ryantrinkle** [comment]
Copying to `rts_js_p_dyn.yaml` and `rts_js_debug_p_dyn.yaml` didn't seem to have any effect, unfortunately.

**Comment by Mikolaj** [comment]
I can now compile successfully in profiling mode on the 8.6 branch with cabal new-build. Closing.
