### ISSUE TITLE
`wrapper` and `dynamic` for ccall imports don't work as expected.

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs#536]
```haskell
foreign import javascript unsafe
  "$r1=function (i) {return i+3;}; $r2=0;" add :: FunPtr (Int -> Int)

foreign import ccall "dynamic"
  mkIntInt :: FunPtr (Int -> Int) -> (Int -> Int)

testAdd :: IO ()
testAdd = do
  putStrLn $ show (mkIntInt add $ 3)

multiple :: Int -> Int
multiple x = x * 3

foreign import ccall "wrapper"
  mkFunIntInt :: (Int -> Int) -> IO (FunPtr (Int -> Int))

testMultiple :: IO ()
testMultiple = do
  fptrIntInt <- mkFunIntInt multiple
  putStrLn $ show (mkIntInt fptrIntInt $ 3)
```

In the above snippet, `testAdd` prints 6. `testMultiple` gives the following output.

```
uncaught exception in Haskell main thread: TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at h$callDynamic (eval at h$loadCodeStr (/home/crocket/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/irunner.js:185:8), <anonymous>:5446:13)
    at h$$mainZCTest_1 (eval at h$loadCodeStr (/home/crocket/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/irunner.js:185:8), <anonymous>:41075:10)
    at h$runThreadSlice (eval at h$loadCodeStr (/home/crocket/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/irunner.js:185:8), <anonymous>:9864:11)
    at h$runThreadSliceCatch (eval at h$loadCodeStr (/home/crocket/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/irunner.js:185:8), <anonymous>:9823:12)
    at Immediate.h$mainLoop [as _callback] (eval at h$loadCodeStr (/home/crocket/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/irunner
```

I conjecture that `wrapper` has a bug. I don't know if `dynamic` has a bug, too, but it's worth checking out.

**Comment by luite** [comment]
If I recall correctly I didn't quite finish the implementation of this feature. I think the representation of the function pointer with `FunPtr` (which has an `Addr#`) made this a tad awkard in JS.
