### ISSUE TITLE
Enabling "-O1" causes exception "TypeError: Cannot read property 'd1' of undefined" (for package Earley)

### ISSUE THREAD

**Issue by phlummox** [ghcjs/ghcjs#539]
This error occurs in Earley-0.11.0.1, with ghcjs version 0.2.0 (GHC 7.10.2). But I believe it occurs with other ghcjs versions as well.

Building with "-O1" (the default, when building with `stack` and `cabal`) causes JavaScript code calling the Earley parsing routines to terminate with the following error (the stack trace may vary):

      uncaught exception in Haskell main thread: TypeError: Cannot read property 'd1' of undefined
      TypeError: Cannot read property 'd1' of undefined
          at h$$yX (Earley-0.11.0.1/dist/build/earley-english/earley-english.jsexe/all.js:47153:15)
          at h$runThreadSlice (Earley-0.11.0.1/dist/build/earley-english/earley-english.jsexe/all.js:9849:11)
          at h$runThreadSliceCatch (Earley-0.11.0.1/dist/build/earley-english/earley-english.jsexe/all.js:9804:12)
          at Object.h$mainLoop (Earley-0.11.0.1/dist/build/earley-english/earley-english.jsexe/all.js:9799:9)
          at processImmediate [as _immediateCallback] (timers.js:354:15)

  Steps to reproduce: 
  run the following shell script (the patch enables building of one of the example executables so it can be run):

      #!/usr/bin/env bash
      cabal get Earley-0.11.0.1 
      cd Earley-0.11.0.1/
      cabal sandbox init
      cabal install --ghcjs --dependencies-only
      cat << EOF > patch
      diff --git a/Earley.cabal b/Earley.cabal
      --- a/Earley.cabal
      +++ b/Earley.cabal
      @@ -43,7 +43,7 @@
       
       executable earley-english
         if !flag(examples)
      -    buildable:         False
      +    buildable:         True
         main-is:             English.hs
         ghc-options:         -Wall
         hs-source-dirs:      examples
      EOF
      patch < ./patch
      cabal configure --ghcjs -O1
      cabal build 
      cabal run earley-english

And the error given above should appear. However, if you replace "-O1" with "-O0", the test program runs normally.
&nbsp; &nbsp;  The Earley package runs perfectly well under ghc - I've used it many times, building with both Cabal and stack. It is only ghcjs that seems to cause a problem, and then only with the "-O1" optimizations. Unfortunately, I'm not very familiar with the details of the -O1 optimizations, and wasn't able to track down which one was causing the problem.
&nbsp; &nbsp;  I can see that Earley makes use of \#INLINE and \#SPECIALIZE pragmas (in the `Text.Earley.Internal` module), so perhaps one of those is causing the problem. Possibly @benzrf has encountered the problem too - I saw mention of something similar in IRC chat logs ([here](http://chrisdone.com:10001/browse/ghcjs?id=182828&timestamp=1470843001#t1470843001)).

**Comment by benzrf** [comment]
+1

**Comment by fisx** [comment]
We had the same issue with stack lts-7.14 and ghcjs-0.2.1.9007014_ghc-8.0.1, and `-O0` didn't appear to help.  Unfortunately, the code isn't public yet, and we had very little time to investigate so far.  Reverting to lts-7.1 made the issue go away.

**Comment by fisx** [comment]
Actually, the error message was subtly different:

```
uncaught exception in Haskell thread: TypeError: Cannot read property 't' of undefined
    at h$e (frontend.js:18654)
    at h$$b0w (frontend.js:147416)
    at h$runThreadSlice (frontend.js:7995)
    at h$runThreadSliceCatch (frontend.js:7952)
    at h$mainLoop (frontend.js:7947)
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

Similar issues:#270, #477.  (I know little about ghcjs internals, so I may be off here.)

(thanks @NicoleRauch)
