### ISSUE TITLE
Problems with closure's ADVANCED_OPTIMIZATIONS

### ISSUE THREAD

**Issue by meditans** [ghcjs/ghcjs#543]
Hi, I wrote a [simple program](https://github.com/meditans/haskell-webapps/tree/master/UI/ReflexFRP/mockLoginPage) using reflex-frp, and I'm trying to minify it with the closure compiler.

The closure compiler is able to compress the generated js, but when the flag `ADVANCED_OPTIMIZATIONS` is enabled I get the error:

```
uncaught exception in Haskell main thread: TypeError: $a$jscomp$2842_f$jscomp$986$$ is undefined
````

I saw that a github issue suggested to add the `--process_jquery_primitives` flag the problem with that is that I cannot run that flag with `ADVANCED_OPTIMIZATIONS`; I'm using the ccjs wrapped version of the closure compiler, as exemplified in the ghcjs wiki. The actual invocation I have problems with is (I added the `--debug` flag):

```
ccjs all.js --debug --compilation_level=ADVANCED_OPTIMIZATIONS > all.min.js
```

The error I can read from the browser console issue is:

```
uncaught exception in Haskell main thread: TypeError: $a$jscomp$2842_f$jscomp$986$$ is undefinedall.min.js:373:25
$h$$aIA$$@http://localhost:8081/all.min.js:4729:64
$h$runThreadSlice$$@http://localhost:8081/all.min.js:412:105
$h$mainLoop$$@http://localhost:8081/all.min.js:408:448
$partiallyApplied$$/<@http://localhost:8081/all.min.js:131:389
$runIfPresent$$@http://localhost:8081/all.min.js:132:124
$onGlobalMessage$$@http://localhost:8081/all.min.js:133:1
all.min.js:373:25
uncaught exception: Thread aborted, exit code: 0(unknown)
```

If I try to invoke directly this with the command `node all.min.js` (as suggested by @luite), I get:

```
uncaught exception in Haskell main thread: ReferenceError: window is not defined
ReferenceError: window is not defined
    at h$ghcjszmdomzm0zi2zi4zi0zm8TojzzGsEq63I8VX8VkXYBVZCGHCJSziDOMzicurrentWindow1_e (/home/carlo/code/haskell/goa/haskell-webapps/UI/ReflexFRP/mockLoginPage/mockClient/js/all.min.js:8171:31)
    at $h$runThreadSlice$$ (/home/carlo/code/haskell/goa/haskell-webapps/UI/ReflexFRP/mockLoginPage/mockClient/js/all.min.js:411:71)
    at Immediate.$h$mainLoop$$ (/home/carlo/code/haskell/goa/haskell-webapps/UI/ReflexFRP/mockLoginPage/mockClient/js/all.min.js:408:448)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

/home/carlo/code/haskell/goa/haskell-webapps/UI/ReflexFRP/mockLoginPage/mockClient/js/all.min.js:426
function $h$exitProcess$$($code$jscomp$5$$){if($h$currentThread$$)throw $h$finishThread$$($h$currentThread$$),$h$stack$$=null,new $h$ThreadAbortedError$$($code$jscomp$5$$);}var $h$mvarId$$=0;function $h$MVar$$(){this.$val$=null;this.$readers$=new $h$Queue$$;this.$writers$=new $h$Queue$$;this.$waiters$=null;this.$m$=0;this.id=++$h$mvarId$$}
                                                                  ^
Thread aborted, exit code: 0
```

Which doesn't seem related. What could I do to better understand this problem? What additional info are needed?

**Comment by dmjio** [comment]
@meditans if you have custom javascript it will be a lot harder to take advantage of `ADVANCED_OPTIMIZATIONS` (I've run into this as well), I'd first find out where `jscomp` is defined (from the error above). Also, if you're running `node` from the command line, there will be no browser present, therefore `window / document` will not be defined, since no DOM exists.

If you can replace calls to `jQuery` with raw DOM calls (using `ghcjs-dom`) you'll probably have more luck with `ADVANCED_OPTIMIIZATIONS`

**Comment by luite** [comment]
It's not just third party JS that breaks at the moment.

I've found a bug recently that broke ADVANCED_OPTIMIZATIONS. I'm almost done with some linker improvements that include the fix.

**Comment by luite** [comment]
decided to push the fix separately. on the ghc-8.0 branc, ghcjs now generates an `all.js.externs` file. if you tell closure compiler to use that as an externs file,`ADVANCED_OPTIMIZATIONS` should work
