### ISSUE TITLE
three line program that crashes ghc-8.0 branch of ghcjs

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs#612]
Compiler built with head on October 12th.

    {-# LANGUAGE TemplateHaskell #-}

    import Control.Lens ({-Iso', iso,-} makeLenses)
    data S = S {_visited :: Int}
    $(makeLenses ''S)

    -- visited :: Iso' S Int
    -- visited = iso (\ (S x) -> x) S
    -- {-# INLINE visited #-}

Result:

    uncaught exception in Haskell main thread: TypeError: Cannot read property 'buf' of null
    TypeError: Cannot read property 'buf' of null
        at h$comparePointer (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:4766:30)
        at h$baseZCGHCziStackziCCSzizdwgo_e (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:35099:13)
        at h$runThreadSlice (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:8241:11)
        at h$runThreadSliceCatch (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:8193:12)
        at h$mainLoop (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:8188:9)
        at eval (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:177:10), <anonymous>:8754:13)
        at /usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:133:9
        at h$processQueue (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:109:13)
        at Socket.<anonymous> (/usr/lib/ghcjs/.ghcjs/x86_64-linux-0.2.1-8.0.2/ghcjs/thrunner.js:76:17)
        at emitNone (events.js:91:20)
    Data.Binary.Get.runGet at position 0: not enough bytes
    CallStack (from HasCallStack):
      error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get

**Comment by cyungmann** [comment]
Most likely occurs because something in `makeLenses` is calling [GHC.Stack.CCS.ccsToStrings](https://www.stackage.org/haddock/lts-9.10/base-4.9.1.0/src/GHC-Stack-CCS.html#ccsToStrings), which compares a `Ptr` with `nullPtr`. However, [`h$comparePointer`](https://github.com/ghcjs/shims/blob/78e2967c791ef29f0f752761a0cd0403ba89777e/src/mem.js#L1017), which is essentially the `Ord` implementation for pointers in GHCJS, does not properly handle `nullPtr`, which gets translated to `null` in JavaScript. It always tries to access the `buf` field on the inputs, which causes an error when one or both of the inputs is `null`. @hamishmack introduced `h$comparePointer` in ghcjs/shims@78e2967c791ef29f0f752761a0cd0403ba89777e

Here is another simple program that causes a crash:

```haskell
import Foreign.Ptr
main = print $ nullPtr > nullPtr
```

@hamishmack, should I try to create a PR with a fix?

**Comment by ddssff** [comment]
@cyungmann - fixes are good!

**Comment by luite** [comment]
Hmm I thought this should have worked already, although comparison only
worked predictably within a single buffer.

**Comment by ddssff** [comment]
Any workaround?

**Comment by cyungmann** [comment]
@ddssff I believe ghcjs/shims#44 should fix it.

**Comment by ddssff** [comment]
Thanks, this fixed the problem for me.  Unfortunately it re-exposes the "TypeError: Cannot read property 'd1' of null" run time problem we had previously.  But now I guess we know they are unrelated.

**Comment by ddssff** [comment]
The property d1 error is now resolved for me.  Closing.

**Comment by cliffordbeshers** [comment]
This was caused by the use of unsafeCoerce in a Functor instance.  Luite
mentioned recently that unsafeCoerce could cause this, so I went looking,
wrote a proper instance and now everything is fine.
