### ISSUE TITLE
8.0: h$comparePointer is not defined

### ISSUE THREAD

**Issue by ElvishJerricco** [ghcjs/ghcjs#633]
Trying to build aeson with the latest 8.0 branch, I'm getting this error:

```
Building aeson-1.2.2.0...
Preprocessing library aeson-1.2.2.0...
[ 1 of 23] Compiling Data.Attoparsec.Time.Internal ( attoparsec-iso8601/Data/Attoparsec/Time/Internal.hs, dist/build/Data/Attoparsec/Time/Internal.js_o )
[ 2 of 23] Compiling Data.Attoparsec.Time ( attoparsec-iso8601/Data/Attoparsec/Time.hs, dist/build/Data/Attoparsec/Time.js_o )
[ 3 of 23] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, dist/build/Data/Aeson/Types/Internal.js_o )
[ 4 of 23] Compiling Data.Aeson.Types.Generic ( Data/Aeson/Types/Generic.hs, dist/build/Data/Aeson/Types/Generic.js_o )
[ 5 of 23] Compiling Data.Aeson.Parser.UnescapePure ( pure/Data/Aeson/Parser/UnescapePure.hs, dist/build/Data/Aeson/Parser/UnescapePure.js_o )
[ 6 of 23] Compiling Data.Aeson.Parser.Unescape ( Data/Aeson/Parser/Unescape.hs, dist/build/Data/Aeson/Parser/Unescape.js_o )
[ 7 of 23] Compiling Data.Aeson.Parser.Time ( Data/Aeson/Parser/Time.hs, dist/build/Data/Aeson/Parser/Time.js_o )
[ 8 of 23] Compiling Data.Aeson.Parser.Internal ( Data/Aeson/Parser/Internal.hs, dist/build/Data/Aeson/Parser/Internal.js_o )
[ 9 of 23] Compiling Data.Aeson.Parser ( Data/Aeson/Parser.hs, dist/build/Data/Aeson/Parser.js_o )
[10 of 23] Compiling Data.Aeson.Internal.Time ( Data/Aeson/Internal/Time.hs, dist/build/Data/Aeson/Internal/Time.js_o )
[11 of 23] Compiling Data.Aeson.Internal.Functions ( Data/Aeson/Internal/Functions.hs, dist/build/Data/Aeson/Internal/Functions.js_o )
[12 of 23] Compiling Data.Aeson.Types.FromJSON ( Data/Aeson/Types/FromJSON.hs, dist/build/Data/Aeson/Types/FromJSON.js_o )

Data/Aeson/Types/FromJSON.hs:471:3: warning: [-Winline-rule-shadowing]
    Rule "FromJSONKeyCoerce: fmap id" may never fire
      because ‘id’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’
[13 of 23] Compiling Data.Aeson.Internal ( Data/Aeson/Internal.hs, dist/build/Data/Aeson/Internal.js_o )
[14 of 23] Compiling Data.Aeson.Encoding.Builder ( Data/Aeson/Encoding/Builder.hs, dist/build/Data/Aeson/Encoding/Builder.js_o )
[15 of 23] Compiling Data.Aeson.Encoding.Internal ( Data/Aeson/Encoding/Internal.hs, dist/build/Data/Aeson/Encoding/Internal.js_o )
[16 of 23] Compiling Data.Aeson.Encoding ( Data/Aeson/Encoding.hs, dist/build/Data/Aeson/Encoding.js_o )
[17 of 23] Compiling Data.Aeson.Types.ToJSON ( Data/Aeson/Types/ToJSON.hs, dist/build/Data/Aeson/Types/ToJSON.js_o )
Linking Template Haskell ()
runNodeInteractive
Linking Template Haskell (Data.Aeson.Encoding,Data.Aeson.Encoding.Builder,Data.Aeson.Encoding.Internal,Data.Aeson.Internal,Data.Aeson.Internal.Functions,Data.Aeson.Internal.Time,Data.Aeson.Parser,Data.Aeson.Parser.Internal,Data.Aeson.Parser.Time,Data.Aeson.Parser.Unescape,Data.Aeson.Parser.UnescapePure,Data.Aeson.Types.FromJSON,Data.Aeson.Types.Generic,Data.Aeson.Types.Internal,Data.Attoparsec.Time,Data.Attoparsec.Time.Internal,ThRunner1)
uncaught exception in Haskell main thread: ReferenceError: h$comparePointer is not defined
ReferenceError: h$comparePointer is not defined
    at h$$binaryzm0zi8zi3zi0zmDu5nfGQyEWO3K75UhFCfsOZCDataziBinaryziClass_Zb7 (eval at h$loadCodeStr (/nix/store/m9khns2y0wllrs12m8vb277l2ffpf6ra-ghcjs-0.2.120171220/lib/ghcjs-0.2.120171220/thrunner.js:177:10), <anonymous>:126463:15)
    at h$runThreadSlice (eval at h$loadCodeStr (/nix/store/m9khns2y0wllrs12m8vb277l2ffpf6ra-ghcjs-0.2.120171220/lib/ghcjs-0.2.120171220/thrunner.js:177:10), <anonymous>:8277:11)
    at h$runThreadSliceCatch (eval at h$loadCodeStr (/nix/store/m9khns2y0wllrs12m8vb277l2ffpf6ra-ghcjs-0.2.120171220/lib/ghcjs-0.2.120171220/thrunner.js:177:10), <anonymous>:8227:12)
    at Immediate.h$mainLoop [as _callback] (eval at h$loadCodeStr (/nix/store/m9khns2y0wllrs12m8vb277l2ffpf6ra-ghcjs-0.2.120171220/lib/ghcjs-0.2.120171220/thrunner.js:177:10), <anonymous>:8222:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

I'm building GHCJS with a merge of these two branches of nixpkgs: https://github.com/NixOS/nixpkgs/pull/37843, https://github.com/NixOS/nixpkgs/pull/37842

**Comment by luite** [comment]
looks like you also need to bump the shims git reference in `head_shims.nix`

**Comment by ElvishJerricco** [comment]
Ah, whoops. @luite I just tried bumping that, but it didn't seem to fix it.

**Comment by luite** [comment]
hm, then I'm not sure what's going on. what can I do to investigate?

**Comment by ElvishJerricco** [comment]
@luite Are you able to build `aeson` with the 8.0 branch?

**Comment by luite** [comment]
yes, building `aeson` as part of the `ghcjs-boot` process works here. (it's a stage2 package, nix skips those. but there's nothing special about building stage2 packages)

**Comment by ElvishJerricco** [comment]
@luite Hm. Well, if you want exact repro steps, try bumping the revisions of GHCJS in nixpkgs to the latest 8.0 and try `nix-build -A haskell.packages.ghcjsHEAD.aeson`
