### ISSUE TITLE
unexpected closure type: 2

### ISSUE THREAD

**Issue by basvandijk** [ghcjs/ghcjs#635]
As initially mentioned in https://github.com/dmjio/miso/pull/377#issuecomment-376348120 running the [bench-queues](https://github.com/basvandijk/bench-queues) executable almost always results in a crash with a message like:

```
uncaught exception in Haskell thread: h$ap_1_1_fast: unexpected closure type: 2
```

This never happens with benchmark A but almost always happens with benchmark B.

I'm using GHCJS https://github.com/ghcjs/ghcjs/commit/2b3759942fb5b2fc1a58d314d9b098d4622fa6b6.

I'll try to make the program even smaller so it will be easier to debug.

**Comment by luite** [comment]
ah yes small example to reproduce this would be very useful. it could be a bug in the code generator, RTS or library. Basically anything that does something equivalent to `unsafeCoerce` can cause this (closure type 2 is a data constructor, it's trying to apply that to one argument, so obviously a function is expected, closure type 1)

**Comment by luite** [comment]
The 8.2 branch has a new flag, `-fruntime-assertions` (hmm, I think I should reconsider the name) that inspects all values at runtime, checking if they are of the expected type (and some invariants). It makes the code much bigger/slower, but perhaps it can help for finding out what goes wrong.

A smaller example would still help, but if you have something that builds on 8.2 I can look into it.

**Comment by harendra-kumar** [comment]
I am also seeing the same issue when I use `streamly` with ghcjs and [run this test](https://github.com/composewell/streamly/blob/84d1b0abf58d6c5cbf57f6a3658bc247100e72ee/test/MaxRate.hs#L84) at 100000 or 1000000 rate.

```
uncaught exception in Haskell thread: h$ap_1_1_fast: unexpected closure type: 2
```

Streamly has a pretty similar buffering queue as described in the benchmark above. I see the issue at higher traffic rates in the test, but not at lower traffic rates. Unfortunately making a smaller example from my code seems difficult, but I guess the example above is small enough.

**Comment by harendra-kumar** [comment]
In the same test, I also see errors like these:

```
uncaught exception in Haskell thread: TypeError: Cannot read property 'd1' of undefined
TypeError: Cannot read property 'd1' of undefined
    at h$$aYh (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:102691:12)
    at h$runThreadSlice (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8272:11)
    at h$runThreadSliceCatch (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8239:12)
    at Immediate.h$mainLoop [as _callback] (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8232:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

```
uncaught exception in Haskell thread: TypeError: Cannot read property 'd1' of undefined
TypeError: Cannot read property 'd1' of undefined
    at h$$aYl (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:102656:12)
    at h$runThreadSlice (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8272:11)
    at h$runThreadSliceCatch (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8239:12)
    at h$mainLoop (/vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8232:9)
    at /vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:8850:13
    at /vol/hosts/cueball/workspace/packages/streamly/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/streamly-0.6.1/t/maxrate/build/maxrate/maxrate.jsexe/all.js:23282:17
    at FSReqWrap.wrapper [as oncomplete] (fs.js:698:5)
```
