### ISSUE TITLE
regex failure

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs#649]
The regex-posix package builds and installs, but using it is causing a runtime error.  I know that regex-posix include C code, should we expect such code to work?

    import Text.Regex

    main :: IO ()
    main = do
      putStrLn $ show $
        matchRegex (mkRegex "^([ \t]*\\$[ \t]*)?([0-9,]*\\.[0-9][0-9]|[0-9,]+)") "<p>$700,000</p>"

    $ ghcjs Foo.hs -o foo && nodejs ./foo.jsexe/all.js
    ghcjs Foo.hs -o foo && nodejs ./foo.jsexe/all.js
    [1 of 1] Compiling Main             ( Foo.hs, Foo.js_o )
    Linking foo.jsexe (Main)
    uncaught exception in Haskell main thread: ReferenceError: h$myregfree is not defined
    ReferenceError: h$myregfree is not defined
        at h$$rq (/home/dsf/git3/happstack-ghcjs/happstack-ghcjs-client/client/AppraisalScribe/foo.jsexe/all.js:41417:26)
        at h$runThreadSlice (/home/dsf/git3/happstack-ghcjs/happstack-ghcjs-  client/client/AppraisalScribe/foo.jsexe/all.js:8248:11)
        at h$runThreadSliceCatch (/home/dsf/git3/happstack-ghcjs/happstack-ghcjs-  client/client/AppraisalScribe/foo.jsexe/all.js:8202:12)
        at Immediate.h$mainLoop [as _callback] (/home/dsf/git3/happstack-ghcjs/happstack-ghcjs-  client/client/AppraisalScribe/foo.jsexe/all.js:8197:9)
        at runCallback (timers.js:649:20)
        at tryOnImmediate (timers.js:622:5)
        at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by luite** [comment]
there is no cabal or link-time check for non-haskell dependencies, so this is what you see.

GHCJS in the `ghc-8.2` branch produces get a report (`out.frefs.json`) of all the referenced foreign code from Haskell, so you can check if anything is missing. There is also `out.frefs.js` that can be loaded in the same JS environment as the Haskell program and prints warnings for things that are potential problems or missing libraries.

**Comment by ddssff** [comment]
Closing this because its not a bug strictly speaking.
