### ISSUE TITLE
8.4: Tests tend to get stuck permanently

### ISSUE THREAD

**Issue by FPtje** [ghcjs/ghcjs#711]
I'm working on getting ghcjs 8.4 to work with our packages. I'm using nixpkgs on `release-18.09`, and I've modified the `ghcjs84` compiler to use revision dc190b1bb2453cfa484124e9f335ee3cad1492f7 and include the patch I posted for #710.

As I was working on getting the packages to compile, I found that quite a few packages took an extremely long time to test. Each time I've had to cancel the build after like an hour. Every time the CPU would be doing basically nothing, and `iotop` shows pretty much no activity either. I didn't think much of it until it started happening to my own packages. Since it's easier to go into a `nix shell` with your own packages, I did just that. `cabal test` reproduced the test getting stuck, but when I ran the test executable manually, I found this error:

```
ReferenceError: h$crypto_scrypt is not defined
    at h$$bla (SOMEHASKELLPACKAGE/dist/build/test-HASKELLPACKAGE/test-HASKELLPACKAGE:120905:11)
    at h$runThreadSlice (SOMEHASKELLPACKAGE/dist/build/test-HASKELLPACKAGE/test-HASKELLPACKAGE:8733:11)
    at h$runThreadSliceCatch (SOMEHASKELLPACKAGE/dist/build/test-HASKELLPACKAGE/test-HASKELLPACKAGE:8688:12)
    at Immediate.h$mainLoop [as _callback] (SOMEHASKELLPACKAGE/dist/build/test-HASKELLPACKAGE/test-HASKELLPACKAGE:8683:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  Json
    Lock
      toValueReversible: 
```

That error is thrown, after which the program will do seemingly nothing. `strace` will show it's sleeping for seconds at a time.

# Reproducing

The error above is from a private package, but a similar error occurs with `tasty-quickcheck`. 
- Download `tasty-quickcheck` version `0.10`, the repo is here: https://github.com/feuerbach/tasty
- `cd` into the `quickcheck` folder
- Get the dependencies using your favourite dependency manager, I used our own nix environment:
```bash
nix-shell default.nix -A pkgs.haskell.packages.ghcjs.tasty-quickcheck.env 
```
- `cabal configure --ghcjs --enable-tests` using ghcjs from the `ghc-8.4` branch
- `cabal test` to find it getting stuck
- `dist/build/test/test` to see the following error:

```
[nix-shell:~/Programs/tasty/quickcheck]$ dist/build/test/test
Unit tests for Test.Tasty.QuickCheck
uncaught exception in Haskell thread: ReferenceError: h$pcre_compile is not defined
ReferenceError: h$pcre_compile is not defined
    at h$$bhc (/somePath/tasty/quickcheck/dist/build/test/test:116097:11)
    at h$runThreadSlice (/somePath/tasty/quickcheck/dist/build/test/test:8735:11)
    at h$runThreadSliceCatch (/somePath/tasty/quickcheck/dist/build/test/test:8688:12)
    at Immediate.h$mainLoop [as _callback] (/somePath/tasty/quickcheck/dist/build/test/test:8683:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  Success:                   
```

Note that this is *also* a `not defined` error, but this time it's `h$pcre_compile`.

For completeness, the same can do with another package called `cryptonite`:
```
[nix-shell:~/Programs/cryptonite]$ dist/build/test-cryptonite/test-cryptonite
uncaught exception in Haskell thread: ReferenceError: h$ghcjsbn_sizeInBase_b is not defined
ReferenceError: h$ghcjsbn_sizeInBase_b is not defined
    at h$integerzmgmpZCGHCziIntegerziGMPziInternalszijszusizzeInBaseBigNat_e (/somePath/cryptonite/dist/build/test-cryptonite/test-cryptonite:97620:11)
    at h$runThreadSlice (/somePath/cryptonite/dist/build/test-cryptonite/test-cryptonite:8731:11)
    at h$runThreadSliceCatch (/somePath/cryptonite/dist/build/test-cryptonite/test-cryptonite:8688:12)
    at Immediate.h$mainLoop [as _callback] (/somePath/cryptonite/dist/build/test-cryptonite/test-cryptonite:8683:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
cryptonite
  number
    num-bits:
```

This doesn't happen in ghcjs 8.0.2. It looks like a regression from either ghcjs or some low level package. The problem is, I'm not sure how to debug this. Since they all seem to be javascript runtime errors, I *guess* it's ghcjs. But what could be the cause?

**Comment by basvandijk** [comment]
Note that both [`crypto_scrypt `](https://github.com/informatikr/scrypt/blob/master/src/Crypto/Scrypt.hs#L251) and [`pcre_compile`](https://github.com/Daniel-Diaz/pcre-light/blob/7ba3e6b874c0ecb8b9df7c6d732410c4e3795449/Text/Regex/PCRE/Light/Base.hsc#L763) are foreign ccalls.

**Comment by luite** [comment]
Yes, this is caused by the tests now depending on this foreign code.
Perhaps some indirect dependency changed.

In the past I've added support in shims for foreign libraries that are
often used in tests. Maybe this is now the easiest way again. Or the
package itself can be updated.

GHCJS outputs a list of foreign calls in a jsexe, so you can check more
easily if anything is missing.

The list is also produced in JSON form, so it can be used for checking at
runtime if everything is there.

**Comment by ddssff** [comment]
I recommend not building regex-pcre and friends, they are just wrappers for C libraries that cannot work in ghcjs.  If you really need regexps the regex-tdfa package is a drop-in replacement with a native Haskell implementation.  Dependencies that use regex-pcre can be modified to use regex-tdfa.
