### ISSUE TITLE
Huge performance regression from ghcjs-8.6.0.1 to ghcjs-8.10.7

### ISSUE THREAD

**Issue by tysonzero** [ghcjs/ghcjs#821]
On ghcjs-8.6.0.1 our project takes on the order of an hour or two to compile, but on ghcjs-8.10.7 it takes closer to a full day.

Memory usage may be a significant reason, as on ghcjs-8.6.0.1 memory usage generally hovers around 20GB, whereas ghcjs-8.10.7 frequently breaks past 30GB.

This is for a ~550 module ~50k LOC project, building on a 32GB memory x86 Mac.

**Comment by ddssff** [comment]
We upgraded all our machines to 64 or 128 GB, and we are still using version 8.6.0.1.  It would be interesting to see what the performance difference of 8.10.7 is on machines with more memory.

**Comment by cliffordbeshers** [comment]
How extensive is your use of Template Haskell?

**Comment by tysonzero** [comment]
On our 64GB Linux boxes it seems slower than 8.6 but by a significantly less ridiculous margin.

However it fails before completion with

```
Data.Binary.Get.runGet at position 0: not enough bytes
```

We use a decent amount of TemplateHaskell, mainly just a `makeLenses` call in most types files, plus some large persistent splices in the db modules.

**Comment by ddssff** [comment]
We eliminated most of our template haskell using https://hackage.haskell.org/package/generic-lens.   I also have a trick which lets you have ghc generate your template haskell in a relatively safe fashion, assuming the module can be compiled by both ghc and ghcjs.   Although I still haven't established what makes some template haskell run fairly quickly and other intolerably slowly.

**Comment by ddssff** [comment]
Do you have large numbers of constraints (maybe via ConstraintKinds) in your signatures?

**Comment by tysonzero** [comment]
We have a moderate amount of constraints, but I wouldn't say a particularly large number, and we do not use ConstraintKinds.

Our database calling functions are generally all polymorphic over `SqlBackendCan[Read|Write]` and `MonadIO`, so they can be used in different contexts (web vs email vs command line).

Besides that most of the functions we define are monomorphic.

**Comment by smelc** [comment]
After upgrading from ghcjs `8.6.0.1` to `8.10.7`, I am witnessing that the linking step, like this:

```
Linking /home/churlin/PERSONNEL/miso-darkcraw/app/dist-newstyle/build/js-ghcjs/ghcjs-8.10.7/app-0.1.0.0/x/app/build/app/app.jsexe (AI,Art,Board,BoardInstances,Campaign,Card,CardInstances,Cinema,Command,Configuration,Constants,Damage,Debugging,DeckView,Event,Game,GameView,GameViewInternal,Json,JsonData,LootView,Main,Model,Movie,MultiPlayerLobbyView,Nat,PCWViewInternal,ServerMessages,SharedModel,SinglePlayerLobbyView,Skill,Spots,Tile,Total,Turn,Update,View,ViewBlocks,ViewInternal,WelcomeView)
````

consumes way more memory than before in my rather modest [project](https://github.com/smelc/miso-darkcraw/tree/master/app). Linking now triggers swapping and a freeze of 15 seconds whereas it was smooth before (I have 16G of ram). I don't use `TH`. I use `ConstraintKinds` in two files which are depended upon by most modules of the project ([Board.hs](https://github.com/smelc/miso-darkcraw/blob/master/app/shared/Board.hs) and [Card.hs](https://github.com/smelc/miso-darkcraw/blob/master/app/shared/Card.hs)).  My project is mostly simple Haskell otherwise.

**Comment by ddssff** [comment]
We managed to compile our system with ghcjs-8.10.7 and the executable size jumped from 70MB to 345MB.

**Comment by tysonzero** [comment]
@ddssff

Obsidian managed to fix the memory / runtime regressions, so we were able to get our project to build, only to find that we ran into the exact same issue, with an even worse ratio: It went from 27MB to 312MB.

**Comment by stepcut** [comment]
I noticed that in `Optimize.hs` the `optimize` function got entirely disabled,

https://github.com/ghcjs/ghcjs/blame/ghc-8.10/src/Gen2/Optimizer.hs#L59

I restored the `optimize` function and the `all.js` generated by with GHCJS 8.10.7 seemed to return to the files size it was with GHCJS 8.6.0.1.  

No idea why it got disabled -- was it a mistake? Or maybe it is buggy? Things seem to be working ok so far, but I have not tested extensively.

@luite mistake or intentional?

**Comment by ddssff** [comment]
Unfortunately there does seem to be an issue with the resulting executable.

    Aug  1 12:58:08.5440: [DEBUG] Base.AppMessage.postAM':158 - request :: GetSourceRows
    rts.js:7285 uncaught exception in Haskell main thread: TypeError: Cannot read properties of undefined (reading 'f')
    rts.js:7285 TypeError: Cannot read properties of undefined (reading 'f')
        at h$$pgD (out.js:717643:13)
        at h$runThreadSlice (rts.js:8463:11)
        at h$runThreadSliceCatch (rts.js:8426:12)
        at h$mainLoop (rts.js:8419:9)
        at rts.js:9045:13
        at XMLHttpRequest.<anonymous> (lib.js:3195:2)
